model:
  target: model.unet.UNet
  params:
    image_size: 224
    in_channels: 9
    out_channels: 1
    unet_channels: [32, 64, 96, 128]
    initial_lr: 1.0e-4

data:
  target: dataset.DegradeSRSliceDataModule
  params:
    data_dir: data/
    batch_size: 8
    num_workers: 4
    slice_axis: 1
    slice_nums: 32
    depth: 9
    cache_mode: memmap
    downsample_scale: 6

trainer:
  devices: [0]
  accelerator: auto
  max_epochs: 15
  check_val_every_n_epoch: 1
  strategy: auto
  precision: 16-mixed
  ckpt_dir: checkpoints/UNet_2p5d
  ckpt_monitor: val/loss
  mode: min

log:
  project: MRI_SR_Tutorial
  name: UNet_2p5d
  log_dir: logs

test_output_dir: results/UNet_2p5d

seed: 24
