model:
  target: model.unet.UNet
  params:
    image_size: 224
    in_channels: 9
    out_channels: 1
    unet_channels: [128, 256, 512, 512]
    initial_lr: 1.0e-4

data:
  target: dataset.DegradeSRSliceDataModule
  params:
    data_dir: data/
    batch_size: 32
    num_workers: 8
    slice_axis: 1
    slice_nums: 128
    depth: 9
    cache_mode: memmap

trainer:
  devices: [0]
  accelerator: auto
  max_epochs: 20
  check_val_every_n_epoch: 1
  strategy: auto
  precision: bf16-mixed
  ckpt_dir: checkpoints/UNet_2p5d_full
  ckpt_monitor: val/loss
  mode: min

log:
  project: MRI_SR_Tutorial
  name: UNet_2p5d_full
  log_dir: logs

test_output_dir: results/UNet_2p5d_full

seed: 24
